### ISSUE TITLE
Doesn't let me open the menu or do anything with the mod

### ISSUE THREAD

**Issue by Barrio2** [ThinkingStudios/Litematica-Forge#21]
The mod appears when clicking the mods button on the main menu, but when I join a world (single or multiplayer) the mod doesnt work. I can't open the menu and it doesnt appear in controls either.

**Comment by OlesiaLulu** [comment]
Same here! Version 1.18.2, Forge 40.2.9. I double-checked, MaFgLib is also there and nothing is working, it doesn't seem to be present anywhere except the Mods menu. I was trying to re-bind buttons because I have a giant mod pack and it's prone to keybinding conflicts, but it's not even present in the Key Settings tab (not sure if it's called that, my version is in a different language).

**Comment by OlesiaLulu** [comment]
I did some digging and apparently, you can bind keys through mode settings, but it's actually pretty hard to figure out which one is responsible for what. It appears to be working though if you're willing to put in the time into binding?

**Comment by Alwax42** [comment]
im haveing the same issue is there a way to fix this

**Comment by Alwax42** [comment]
nvm figured it out

**Comment by Barrio2** [comment]
> nvm figured it out

what did you do, I'm still having the issue

**Comment by TexBlock** [comment]
mod version?
