### ISSUE TITLE
Crash on 1.20.2

### ISSUE THREAD

**Issue by DraconicNEO** [ThinkingStudios/Litematica-Forge#38]
I tried to load the mod on 1.20.2 but it just crashes. I think the mod needs to be updated to support 1.20.2

Crash report:
[crash-2023-12-22_19.30.58-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/13757883/crash-2023-12-22_19.30.58-client.txt)

**Comment by ForgeLoverAndUser** [comment]
its says a lot of stuff about "Critical Error" and it talks a lot about "mixin-0.8.5.jar" maybe try deleting the jar file and its config folder? 

based on your log i will recreate this error on my computer and see how to fix it!

**Comment by ForgeLoverAndUser** [comment]
"org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" Its the jar file or mod you have installed. its not Forgematica, its just because the mixin mod standalone by itself created so many errors that it caused Minecraft to crash. Forgematica has nothing to do with this error. I'd say if mixin has a Github page, create an issue report there.

If you need mixin for your world or situation, i don't have a solution for you. Sorry.

**Comment by DraconicNEO** [comment]
> "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" Its the jar file or mod you have installed. its not Forgematica, its just because the mixin mod standalone by itself created so many errors that it caused Minecraft to crash. Forgematica has nothing to do with this error. I'd say if mixin has a Github page, create an issue report there.
> 
> If you need mixin for your world or situation, i don't have a solution for you. Sorry.

What is mixin exactly? I've never heard of it before.

Also do you know how to disable it on PrismLauncher? I tried deleting it but it just downloads it again.

**Comment by TexBlock** [comment]
NOT SUPPORT 1.20.2 NOW
